use serde::{Deserialize, Serialize};
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct ModelInfo {
    pub id: String,
    #[serde(rename = "display_name")]
    pub name: String,
    pub size_bytes: u64,
    pub downloaded: bool,
    pub active: bool,
    pub download_progress: f32,
    pub description: String,
    pub recommended: bool,
    pub requires: String,
    pub language: String,
    pub quant: String,
    pub license: String,
}

impl ModelInfo {
    pub fn catalog() -> Vec<ModelInfo> {
        vec![
            // ──────────────────────────────────────────────────────────
            //  🏆 RECOMENDADOS PARA MÓVIL
            // ──────────────────────────────────────────────────────────

            // 🥇 Parakeet TDT 0.6B v3 (Q4_K_M) — 485 MB, 25 idiomas europeos
            ModelInfo {
                id: "parakeet-tdt-0.6b-v3-Q4_K_M".into(),
                name: "Parakeet TDT 0.6B v3".into(),
                size_bytes: 485_425_504,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "🏆 RECOMENDADO MÓVIL — NVIDIA Parakeet TDT 0.6B v3. Rápido y preciso. Soporta 25 idiomas europeos. Perfecto para móvil: compacto (485 MB), baja latencia, alta precisión. Mismo modelo recomendado en Handy PC.".into(),
                recommended: true,
                requires: "2 GB RAM".into(),
                language: "bg,hr,cs,da,nl,en,et,fi,fr,de,el,hu,it,lv,lt,mt,pl,pt,ro,ru,sk,sl,es,sv,uk".into(),
                quant: "Q4_K_M".into(),
                license: "CC-BY-4.0".into(),
            },

            // 🥈 Canary 180M Flash (Q4_K_M) — 139 MB, 4 idiomas + traducción
            ModelInfo {
                id: "canary-180m-flash-Q4_K_M".into(),
                name: "Canary 180M Flash (Q4_K_M)".into(),
                size_bytes: 139_223_744,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "🥈 RECOMENDADO MÓVIL — NVIDIA Canary 180M Flash: tiny e instantáneo. 4 idiomas (EN, DE, ES, FR) con traducción a inglés. Solo 139 MB. Corre en cualquier hardware.".into(),
                recommended: true,
                requires: "1 GB RAM".into(),
                language: "en,de,es,fr".into(),
                quant: "Q4_K_M".into(),
                license: "CC-BY-4.0".into(),
            },

            // 🥉 Nemotron 3.5 ASR Streaming 0.6B (Q4_K_M) — 496 MB, 28 idiomas
            ModelInfo {
                id: "nemotron-3.5-asr-streaming-0.6b-Q4_K_M".into(),
                name: "Nemotron Streaming 3.5 (Q4_K_M)".into(),
                size_bytes: 495_831_520,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "🥉 RECOMENDADO MÓVIL — NVIDIA Nemotron 3.5 ASR Streaming: 28 idiomas. Transcripción en vivo con detección automática de idioma. Ideal para usuarios multilingües.".into(),
                recommended: true,
                requires: "2 GB RAM".into(),
                language: "en,es,fr,it,pt,nl,de,tr,ru,ar,hi,ja,ko,vi,uk,pl,sv,cs,nb,da,bg,fi,hr,sk,zh,hu,ro,et".into(),
                quant: "Q4_K_M".into(),
                license: "Other".into(),
            },

            // ⚡ SenseVoice Small (INT8) — 160 MB, latencia ultra-baja (Chino, Inglés, Japonés, Coreano, Cantonés)
            ModelInfo {
                id: "sense-voice-int8".into(),
                name: "SenseVoice Small (INT8)".into(),
                size_bytes: 167_772_160,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "⚡ ULTRA-RÁPIDO MÓVIL — Alibaba SenseVoice Small: latencia extremadamente baja. Soporta Chino, Inglés, Japonés, Coreano y Cantonés. Solo 160 MB.".into(),
                recommended: true,
                requires: "1 GB RAM".into(),
                language: "zh,en,ja,ko,yue".into(),
                quant: "INT8".into(),
                license: "MIT".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  ONNX Parakeet / Canary (transcribe-rs, directory-based)
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "parakeet-tdt-0.6b-v3-int8".into(),
                name: "Parakeet TDT 0.6B v3 ONNX (INT8)".into(),
                size_bytes: 650_000_000,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet TDT 0.6B v3 en formato ONNX INT8 (directorio). Recomendado para transcribe-rs. 25 idiomas europeos.".into(),
                recommended: true,
                requires: "2 GB RAM".into(),
                language: "bg,hr,cs,da,nl,en,et,fi,fr,de,el,hu,it,lv,lt,mt,pl,pt,ro,ru,sk,sl,es,sv,uk".into(),
                quant: "INT8 ONNX".into(),
                license: "CC-BY-4.0".into(),
            },

            ModelInfo {
                id: "canary-180m-flash-int8".into(),
                name: "Canary 180M Flash ONNX (INT8)".into(),
                size_bytes: 250_000_000,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Canary 180M Flash en formato ONNX INT8 (directorio). Rápido y multilingüe (EN, DE, ES, FR) para transcribe-rs.".into(),
                recommended: true,
                requires: "1 GB RAM".into(),
                language: "en,de,es,fr".into(),
                quant: "INT8 ONNX".into(),
                license: "CC-BY-4.0".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  WHISPER (OpenAI) — 99 idiomas, vía whisper.cpp
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "whisper-tiny-Q5_K_M".into(),
                name: "Whisper Tiny (Q5_K_M)".into(),
                size_bytes: 77_000_000,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "El Whisper más rápido, ~32x tiempo real. 99 idiomas. Ideal para dictados cortos y comandos de voz. Mínimo consumo de recursos.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "multilingual".into(),
                quant: "Q5_K_M".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "whisper-base-Q5_K_M".into(),
                name: "Whisper Base (Q5_K_M)".into(),
                size_bytes: 155_000_000,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Buen equilibrio velocidad/precisión. ~16x tiempo real. 99 idiomas. Opción ligera y fiable para el día a día.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "multilingual".into(),
                quant: "Q5_K_M".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "whisper-small-Q5_K_M".into(),
                name: "Whisper Small (Q5_K_M)".into(),
                size_bytes: 488_000_000,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "El mejor equilibrio entre precisión y velocidad. 99 idiomas. Ideal para reuniones, conferencias y uso general. ~6x tiempo real.".into(),
                recommended: false,
                requires: "3 GB RAM".into(),
                language: "multilingual".into(),
                quant: "Q5_K_M".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "whisper-medium-Q4_K_M".into(),
                name: "Whisper Medium (Q4_K_M)".into(),
                size_bytes: 504_102_848,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Alta precisión Whisper. 99 idiomas. Ideal para entornos ruidosos y transcripción larga. ~3x tiempo real.".into(),
                recommended: false,
                requires: "3 GB RAM".into(),
                language: "multilingual".into(),
                quant: "Q4_K_M".into(),
                license: "MIT".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  CANARY (NVIDIA) — 4-25 idiomas, con traducción
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "canary-qwen-2.5b-Q4_K_M".into(),
                name: "Canary-Qwen 2.5B (Q4_K_M)".into(),
                size_bytes: 1_737_575_808,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Canary-Qwen 2.5B: inglés con la máxima precisión. 1.7 GB. Ideal para dispositivos con 4+ GB RAM.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "en".into(),
                quant: "Q4_K_M".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "canary-1b-flash-Q4_K_M".into(),
                name: "Canary 1B Flash (Q4_K_M)".into(),
                size_bytes: 677_141_280,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Canary 1B Flash: gran precisión. 4 idiomas (EN, DE, ES, FR). Soporta traducción a inglés.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en,de,es,fr".into(),
                quant: "Q4_K_M".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "canary-1b-v2-Q4_K_M".into(),
                name: "Canary 1B v2 (Q4_K_M)".into(),
                size_bytes: 735_476_448,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Canary 1B v2: 25 idiomas europeos con traducción a inglés. Versátil y preciso.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "bg,hr,cs,da,nl,en,et,fi,fr,de,el,hu,it,lv,lt,mt,pl,pt,ro,sk,sl,es,sv,ru,uk".into(),
                quant: "Q4_K_M".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "canary-1b-Q4_K_M".into(),
                name: "Canary 1B (Q4_K_M)".into(),
                size_bytes: 729_686_848,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Canary 1B: 4 idiomas (EN, DE, ES, FR). Traducción a inglés incluida. Precisión excelente.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en,de,es,fr".into(),
                quant: "Q4_K_M".into(),
                license: "CC-BY-NC-4.0".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  PARAKEET (NVIDIA) — inglés / solo inglés
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "parakeet-tdt-0.6b-v2-Q4_K_M".into(),
                name: "Parakeet TDT 0.6B v2 (Q4_K_M)".into(),
                size_bytes: 475_491_840,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet TDT 0.6B v2: el mejor modelo para inglés. Precisión superior para hablantes nativos de inglés.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en".into(),
                quant: "Q4_K_M".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "parakeet-unified-en-0.6b-Q4_K_M".into(),
                name: "Parakeet Unified EN 0.6B (Q4_K_M)".into(),
                size_bytes: 477_274_496,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet Unified EN 0.6B: rápido y preciso para inglés. Ideal para transcripción en vivo.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en".into(),
                quant: "Q4_K_M".into(),
                license: "CC-BY-4.0".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  QWEN3-ASR (Alibaba) — 30 idiomas, chino+inglés+árabe+hindi
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "Qwen3-ASR-0.6B-Q4_K_M".into(),
                name: "Qwen3-ASR 0.6B (Q4_K_M)".into(),
                size_bytes: 589_560_480,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Alibaba Qwen3-ASR 0.6B: excelente modelo multilingüe con 30 idiomas. Cubre chino, inglés, árabe, hindi y más.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "zh,en,yue,ar,de,fr,es,pt,id,it,ko,ru,th,vi,ja,tr,hi,ms,nl,sv,da,fi,pl,cs,fil,fa,el,ro,hu,mk".into(),
                quant: "Q4_K_M".into(),
                license: "Apache-2.0".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  FUN-ASR (FunAudioLLM) — asiáticos + europeos
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "Fun-ASR-MLT-Nano-2512-Q4_K_M".into(),
                name: "Fun-ASR Nano Multilingual (Q4_K_M)".into(),
                size_bytes: 556_975_168,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "FunAudioLLM Fun-ASR Nano Multilingual: modelo pequeño con 31 idiomas. Cubre asiáticos y europeos.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "zh,en,yue,ja,ko,vi,id,th,ms,tl,ar,hi,bg,hr,cs,da,nl,et,fi,el,hu,ga,lv,lt,mt,pl,pt,ro,sk,sl,sv".into(),
                quant: "Q4_K_M".into(),
                license: "Other".into(),
            },
            ModelInfo {
                id: "Fun-ASR-Nano-2512-Q4_K_M".into(),
                name: "Fun-ASR Nano (Q4_K_M)".into(),
                size_bytes: 556_974_848,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "FunAudioLLM Fun-ASR Nano: 3 idiomas (ZH, EN, JA). Rápido y ligero para asiáticos orientales.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "zh,en,ja".into(),
                quant: "Q4_K_M".into(),
                license: "Other".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  GIGAAM (ai-sage) — ruso, todas las variantes
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "gigaam-v3-ctc-Q4_K_M".into(),
                name: "GigaAM v3 CTC (Q4_K_M)".into(),
                size_bytes: 182_150_080,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "GigaAM v3 CTC: reconocimiento de voz en ruso. Rápido con marcas de tiempo por token.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "ru".into(),
                quant: "Q4_K_M".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "gigaam-v3-e2e-ctc-Q4_K_M".into(),
                name: "GigaAM v3 E2E-CTC (Q4_K_M)".into(),
                size_bytes: 182_497_888,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "GigaAM v3 E2E-CTC: reconocimiento de voz en ruso con marcas de tiempo por token.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "ru".into(),
                quant: "Q4_K_M".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "gigaam-v3-rnnt-Q4_K_M".into(),
                name: "GigaAM v3 RNN-T (Q4_K_M)".into(),
                size_bytes: 183_246_752,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "GigaAM v3 RNN-T: reconocimiento de voz en ruso con marcas de tiempo por token.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "ru".into(),
                quant: "Q4_K_M".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "gigaam-v3-e2e-rnnt-Q4_K_M".into(),
                name: "GigaAM v3 E2E-RNN-T (Q4_K_M)".into(),
                size_bytes: 183_948_704,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "GigaAM v3 E2E-RNN-T: reconocimiento de voz en ruso con marcas de tiempo por token. La mejor variante GigaAM (accuracy 70).".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "ru".into(),
                quant: "Q4_K_M".into(),
                license: "MIT".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  GRANITE SPEECH (IBM) — 5-6 idiomas, alta precisión
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "granite-speech-4.1-2b-nar-Q4_K_M".into(),
                name: "Granite Speech 4.1 2B NAR (Q4_K_M)".into(),
                size_bytes: 1_560_008_832,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "IBM Granite Speech 4.1 2B NAR: 5 idiomas (EN, FR, DE, ES, PT). Alta precisión (accuracy 92). ~1.6 GB.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "en,fr,de,es,pt".into(),
                quant: "Q4_K_M".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "granite-4.0-1b-speech-Q4_K_M".into(),
                name: "Granite Speech 4.0 1B (Q4_K_M)".into(),
                size_bytes: 1_602_904_800,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "IBM Granite Speech 4.0 1B: 6 idiomas (EN, FR, DE, ES, PT, JA) con traducción. Alta precisión.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "en,fr,de,es,pt,ja".into(),
                quant: "Q4_K_M".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "granite-speech-4.1-2b-Q4_K_M".into(),
                name: "Granite Speech 4.1 2B (Q4_K_M)".into(),
                size_bytes: 1_602_904_800,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "IBM Granite Speech 4.1 2B: 6 idiomas (EN, FR, DE, ES, PT, JA) con traducción. Precisión máxima (accuracy 92).".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "en,fr,de,es,pt,ja".into(),
                quant: "Q4_K_M".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "granite-speech-4.1-2b-plus-Q4_K_M".into(),
                name: "Granite Speech 4.1 2B Plus (Q4_K_M)".into(),
                size_bytes: 1_489_663_424,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "IBM Granite Speech 4.1 2B Plus: 5 idiomas (EN, FR, DE, ES, PT). Marcas de tiempo por palabra. ~1.5 GB.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "en,fr,de,es,pt".into(),
                quant: "Q4_K_M".into(),
                license: "Apache-2.0".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  MEDASR (Google) — inglés, ultraligero 83 MB
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "medasr-Q4_K_M".into(),
                name: "MedASR (Q4_K_M)".into(),
                size_bytes: 83_082_432,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Google MedASR: inglés con marcas de tiempo por token. Ultraligero (83 MB). El más rápido disponible.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "en".into(),
                quant: "Q4_K_M".into(),
                license: "Other".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  MOONSHINE (UsefulSensors) — inglés + 5 idiomas, ultra-ligero
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "moonshine-tiny-Q8_0".into(),
                name: "Moonshine Tiny (Q8_0)".into(),
                size_bytes: 35_466_912,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Tiny: inglés ultraligero. Solo 35 MB. Velocidad máxima, precisión decente (accuracy 74).".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-streaming-tiny-Q8_0".into(),
                name: "Moonshine Streaming Tiny (Q8_0)".into(),
                size_bytes: 50_462_816,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Streaming Tiny: inglés con streaming. 50 MB. Transcripción en tiempo real.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-tiny-vi-Q8_0".into(),
                name: "Moonshine Tiny Vietnamese (Q8_0)".into(),
                size_bytes: 35_466_944,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Tiny: vietnamita. Ultraligero (35 MB).".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "vi".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-tiny-uk-Q8_0".into(),
                name: "Moonshine Tiny Ukrainian (Q8_0)".into(),
                size_bytes: 35_466_944,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Tiny: ucraniano. Ultraligero (35 MB).".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "uk".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-tiny-ko-Q8_0".into(),
                name: "Moonshine Tiny Korean (Q8_0)".into(),
                size_bytes: 35_466_944,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Tiny: coreano. Ultraligero (35 MB).".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "ko".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-tiny-zh-Q8_0".into(),
                name: "Moonshine Tiny Chinese (Q8_0)".into(),
                size_bytes: 35_466_944,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Tiny: chino. Ultraligero (35 MB).".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "zh".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-tiny-ar-Q8_0".into(),
                name: "Moonshine Tiny Arabic (Q8_0)".into(),
                size_bytes: 35_466_944,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Tiny: árabe. Ultraligero (35 MB).".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "ar".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-tiny-ja-Q8_0".into(),
                name: "Moonshine Tiny Japanese (Q8_0)".into(),
                size_bytes: 35_466_944,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Tiny: japonés. Ultraligero (35 MB).".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "ja".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-base-Q8_0".into(),
                name: "Moonshine Base (Q8_0)".into(),
                size_bytes: 77_476_480,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Base: inglés. 77 MB. Precisión mejorada respecto a Tiny.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-base-ar-Q8_0".into(),
                name: "Moonshine Base Arabic (Q8_0)".into(),
                size_bytes: 77_476_480,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Base: árabe. 77 MB.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "ar".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-base-ko-Q8_0".into(),
                name: "Moonshine Base Korean (Q8_0)".into(),
                size_bytes: 77_476_480,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Base: coreano. 77 MB.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "ko".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-base-uk-Q8_0".into(),
                name: "Moonshine Base Ukrainian (Q8_0)".into(),
                size_bytes: 77_476_512,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Base: ucraniano. 77 MB.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "uk".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-base-ja-Q8_0".into(),
                name: "Moonshine Base Japanese (Q8_0)".into(),
                size_bytes: 77_476_480,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Base: japonés. 77 MB.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "ja".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-base-vi-Q8_0".into(),
                name: "Moonshine Base Vietnamese (Q8_0)".into(),
                size_bytes: 77_476_512,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Base: vietnamita. 77 MB.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "vi".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-base-zh-Q8_0".into(),
                name: "Moonshine Base Chinese (Q8_0)".into(),
                size_bytes: 77_476_480,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Base: chino. 77 MB.".into(),
                recommended: false,
                requires: "512 MB RAM".into(),
                language: "zh".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-streaming-small-Q8_0".into(),
                name: "Moonshine Streaming Small (Q8_0)".into(),
                size_bytes: 198_506_848,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Streaming Small: inglés con streaming. 199 MB.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },
            ModelInfo {
                id: "moonshine-streaming-medium-Q8_0".into(),
                name: "Moonshine Streaming Medium (Q8_0)".into(),
                size_bytes: 295_793_568,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "UsefulSensors Moonshine Streaming Medium: inglés con streaming. 296 MB.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "MIT".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  COHERE TRANSCRIBE (Cohere) — 14 idiomas, máxima precisión
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "cohere-transcribe-03-2026-Q4_K_M".into(),
                name: "Cohere Transcribe (Q4_K_M)".into(),
                size_bytes: 1_558_162_944,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Cohere Transcribe 03-2026: 14 idiomas (EN, FR, DE, ES, IT, PT, NL, PL, EL, AR, JA, ZH, VI, KO). La máxima precisión (accuracy 92). ~1.6 GB.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "en,fr,de,es,it,pt,nl,pl,el,ar,ja,zh,vi,ko".into(),
                quant: "Q4_K_M".into(),
                license: "Apache-2.0".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  VOXTRA — Mistral Voxtral Mini 4B Realtime
            //  13 idiomas, streaming, 2.8 GB (requiere hardware potente)
            // ──────────────────────────────────────────────────────────

            ModelInfo {
                id: "Voxtral-Mini-4B-Realtime-2602-Q4_K_M".into(),
                name: "Voxtral Mini 4B Realtime (Q4_K_M)".into(),
                size_bytes: 2_830_493_984,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Mistral Voxtral Mini 4B Realtime: 13 idiomas con streaming. El modelo más grande (2.8 GB). Requiere hardware potente (6+ GB RAM).".into(),
                recommended: false,
                requires: "6 GB RAM".into(),
                language: "en,fr,es,de,ru,zh,ja,it,pt,nl,ar,hi,ko".into(),
                quant: "Q4_K_M".into(),
                license: "Apache-2.0".into(),
            },

            // ──────────────────────────────────────────────────────────
            //  EXTRA PC CATALOG MODELS
            // ──────────────────────────────────────────────────────────

            // ── Nemotron Speech Streaming EN ─────────────────────────
            ModelInfo {
                id: "nemotron-speech-streaming-en-0.6b-Q8_0".into(),
                name: "Nemotron Speech Streaming EN (Q8_0)".into(),
                size_bytes: 729_650_176,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Nemotron Speech Streaming EN: inglés con streaming y marcas de tiempo por token. 730 MB.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "Other".into(),
            },

            // ── Parakeet CTC/RNN/TDT variants ───────────────────────
            ModelInfo {
                id: "parakeet-tdt_ctc-110m-Q8_0".into(),
                name: "Parakeet TDT-CTC 110M (Q8_0)".into(),
                size_bytes: 135_373_280,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet TDT-CTC 110M: inglés ultraligero con marcas de tiempo. 135 MB.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "parakeet-ctc-0.6b-Q8_0".into(),
                name: "Parakeet CTC 0.6B (Q8_0)".into(),
                size_bytes: 722_271_424,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet CTC 0.6B: inglés con marcas de tiempo por token. 722 MB.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "parakeet-rnnt-0.6b-Q8_0".into(),
                name: "Parakeet RNN-T 0.6B (Q8_0)".into(),
                size_bytes: 729_687_456,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet RNN-T 0.6B: inglés con marcas de tiempo por token. 730 MB.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "parakeet-ctc-1.1b-Q5_K_M".into(),
                name: "Parakeet CTC 1.1B (Q5_K_M)".into(),
                size_bytes: 928_584_736,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet CTC 1.1B: inglés con marcas de tiempo por token. 929 MB.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en".into(),
                quant: "Q5_K_M".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "parakeet-tdt-1.1b-Q5_K_M".into(),
                name: "Parakeet TDT 1.1B (Q5_K_M)".into(),
                size_bytes: 935_758_496,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet TDT 1.1B: inglés de alta precisión con marcas de tiempo. 936 MB.".into(),
                recommended: false,
                requires: "3 GB RAM".into(),
                language: "en".into(),
                quant: "Q5_K_M".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "parakeet-rnnt-1.1b-Q5_K_M".into(),
                name: "Parakeet RNN-T 1.1B (Q5_K_M)".into(),
                size_bytes: 935_755_008,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet RNN-T 1.1B: inglés con marcas de tiempo por token. 936 MB.".into(),
                recommended: false,
                requires: "3 GB RAM".into(),
                language: "en".into(),
                quant: "Q5_K_M".into(),
                license: "CC-BY-4.0".into(),
            },
            ModelInfo {
                id: "parakeet-tdt_ctc-1.1b-Q5_K_M".into(),
                name: "Parakeet TDT-CTC 1.1B (Q5_K_M)".into(),
                size_bytes: 935_758_080,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "NVIDIA Parakeet TDT-CTC 1.1B: inglés con marcas de tiempo por token. 936 MB.".into(),
                recommended: false,
                requires: "3 GB RAM".into(),
                language: "en".into(),
                quant: "Q5_K_M".into(),
                license: "CC-BY-4.0".into(),
            },

            // ── Qwen3-ASR 1.7B ──────────────────────────────────────
            ModelInfo {
                id: "Qwen3-ASR-1.7B-Q5_K_M".into(),
                name: "Qwen3-ASR 1.7B (Q5_K_M)".into(),
                size_bytes: 1_517_290_464,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Alibaba Qwen3-ASR 1.7B: 30 idiomas con detección automática de idioma. 1.5 GB. Perfecto para cobertura asiática + europea.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "zh,en,yue,ar,de,fr,es,pt,id,it,ko,ru,th,vi,ja,tr,hi,ms,nl,sv,da,fi,pl,cs,fil,fa,el,ro,hu,mk".into(),
                quant: "Q5_K_M".into(),
                license: "Apache-2.0".into(),
            },

            // ── SenseVoice Small ────────────────────────────────────
            ModelInfo {
                id: "SenseVoiceSmall-Q8_0".into(),
                name: "SenseVoice Small (Q8_0)".into(),
                size_bytes: 252_684_608,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "SenseVoice Small: 5 idiomas (ZH, YUE, EN, JA, KO) con detección automática de idioma. 253 MB.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "zh,yue,en,ja,ko".into(),
                quant: "Q8_0".into(),
                license: "Other".into(),
            },

            // ── Voxtral Mini 3B ─────────────────────────────────────
            ModelInfo {
                id: "Voxtral-Mini-3B-2507-Q5_K_M".into(),
                name: "Voxtral Mini 3B (Q5_K_M)".into(),
                size_bytes: 3_464_182_432,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Mistral Voxtral Mini 3B: 8 idiomas con traducción y detección auto. 3.5 GB.".into(),
                recommended: false,
                requires: "6 GB RAM".into(),
                language: "en,fr,de,es,it,pt,nl,hi".into(),
                quant: "Q5_K_M".into(),
                license: "Apache-2.0".into(),
            },

            // ── Voxtral Small 24B ───────────────────────────────────
            ModelInfo {
                id: "Voxtral-Small-24B-2507-Q5_K_M".into(),
                name: "Voxtral Small 24B (Q5_K_M)".into(),
                size_bytes: 17_138_659_808,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Mistral Voxtral Small 24B: 8 idiomas con traducción. El modelo más grande (17 GB). Solo para hardware extremo.".into(),
                recommended: false,
                requires: "16+ GB RAM".into(),
                language: "en,fr,de,es,it,pt,nl,hi".into(),
                quant: "Q5_K_M".into(),
                license: "Apache-2.0".into(),
            },

            // ── Whisper English-only variants (en) ──────────────────
            ModelInfo {
                id: "whisper-tiny.en-Q8_0".into(),
                name: "Whisper Tiny English (Q8_0)".into(),
                size_bytes: 45_904_544,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "OpenAI Whisper Tiny English-only: inglés con marcas de tiempo por segmento. Solo 46 MB.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "whisper-base.en-Q8_0".into(),
                name: "Whisper Base English (Q8_0)".into(),
                size_bytes: 84_886_208,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "OpenAI Whisper Base English-only: inglés con marcas de tiempo por segmento. 85 MB.".into(),
                recommended: false,
                requires: "1 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "whisper-small.en-Q8_0".into(),
                name: "Whisper Small English (Q8_0)".into(),
                size_bytes: 269_674_144,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "OpenAI Whisper Small English-only: inglés con marcas de tiempo por segmento. 270 MB.".into(),
                recommended: false,
                requires: "2 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "whisper-medium.en-Q8_0".into(),
                name: "Whisper Medium English (Q8_0)".into(),
                size_bytes: 831_460_928,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "OpenAI Whisper Medium English-only: inglés con marcas de tiempo por segmento. 831 MB.".into(),
                recommended: false,
                requires: "3 GB RAM".into(),
                language: "en".into(),
                quant: "Q8_0".into(),
                license: "Apache-2.0".into(),
            },

            // ── Whisper Large variants ──────────────────────────────
            ModelInfo {
                id: "whisper-large-v3-turbo-Q8_0".into(),
                name: "Whisper Large v3 Turbo (Q8_0)".into(),
                size_bytes: 886_381_824,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "OpenAI Whisper Large v3 Turbo: 100 idiomas. Rápido y preciso. 886 MB.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "multilingual".into(),
                quant: "Q8_0".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "whisper-large-v3-Q5_K_M".into(),
                name: "Whisper Large v3 (Q5_K_M)".into(),
                size_bytes: 1_161_143_008,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "OpenAI Whisper Large v3: 100 idiomas. La máxima precisión Whisper. 1.16 GB.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "multilingual".into(),
                quant: "Q5_K_M".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "whisper-large-Q5_K_M".into(),
                name: "Whisper Large (Q5_K_M)".into(),
                size_bytes: 1_160_366_048,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "OpenAI Whisper Large: 99 idiomas. Precisión excelente. 1.16 GB.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "multilingual".into(),
                quant: "Q5_K_M".into(),
                license: "Apache-2.0".into(),
            },
            ModelInfo {
                id: "whisper-large-v2-Q5_K_M".into(),
                name: "Whisper Large v2 (Q5_K_M)".into(),
                size_bytes: 1_160_366_080,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "OpenAI Whisper Large v2: 99 idiomas. Precisión de referencia. 1.16 GB.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "multilingual".into(),
                quant: "Q5_K_M".into(),
                license: "Apache-2.0".into(),
            },

            // ── Breeze-ASR-25 ───────────────────────────────────────
            ModelInfo {
                id: "Breeze-ASR-25-Q5_K_M".into(),
                name: "Breeze-ASR-25 (Q5_K_M)".into(),
                size_bytes: 1_160_366_080,
                downloaded: false,
                active: false,
                download_progress: 0.0,
                description: "Breeze-ASR-25: optimizado para mandarín taiwanés con soporte code-switching ZH/EN. 1.16 GB.".into(),
                recommended: false,
                requires: "4 GB RAM".into(),
                language: "zh,en".into(),
                quant: "Q5_K_M".into(),
                license: "Apache-2.0".into(),
            },
        ]
    }

    pub fn from_filename(path: &Path) -> Option<ModelInfo> {
        let ext = path.extension()?;
        if ext != "gguf" {
            return None;
        }
        let stem = path.file_stem()?.to_str()?;
        let file_size = std::fs::metadata(path).ok().map(|m| m.len()).unwrap_or(0);
        let mut matched = Self::catalog().into_iter().find(|m| m.id == stem)?;
        matched.downloaded = true;
        matched.download_progress = 100.0;
        matched.size_bytes = file_size;
        Some(matched)
    }
}
